### ISSUE TITLE
 can't install this package

### ISSUE THREAD

**Issue by 0x6rss** [harismuneer/AndroCompare#1]
hi, i can't install this package, can you help me please?

└─# python2 andro_compare.py
Traceback (most recent call last):
  File "andro_compare.py", line 5, in <module>
    from apk import APK
  File "./libs/apk.py", line 30, in <module>
    import M2Crypto
ImportError: No module named M2Crypto

**Comment by lauraschauer** [comment]
I have the same problem, is there a solution?

**Comment by lauraschauer** [comment]
Try using `from libs.apk import APK`
